wandb_version: 1

batch_size:
  desc: null
  value: 32
l_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: nadam
epochs:
  desc: null
  value: 5
activation:
  desc: null
  value: relu
initializer:
  desc: null
  value: random
loss:
  desc: null
  value: squared_error
n_hlayers:
  desc: null
  value: 5
hlayer_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710695400.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
    viz:
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
